Fixing certificates for web access

diff --git a/tweaks/apache-enable-ssl-letsencrypt b/tweaks/apache-enable-ssl-letsencrypt
--- a/tweaks/apache-enable-ssl-letsencrypt
+++ b/tweaks/apache-enable-ssl-letsencrypt
@@ -26,6 +26,26 @@ SSLStaplingCache "shmcb:logs/stapling-cache(150000)"
 SSLSessionTickets Off
 EOF
 
+## applying ssl for cc web app ##
+systemctl stop apache2.service
+execSpecial 3 '(fail|error)' certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${CWM_DOMAIN} ${CWM_DEBUG:+"--test-cert"}
+
+if [[ $? == 1 ]]; then
+	export certbot_failed=1
+	echo "Generating self-signed certificate" | log
+	#waitOrStop 0 "Failed certbot certificate generation"
+	mkdir /etc/letsencrypt/live
+	mkdir /etc/letsencrypt/live/${CWM_DOMAIN}
+	openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/letsencrypt/live/${CWM_DOMAIN}/privkey.pem -out /etc/letsencrypt/live/${CWM_DOMAIN}/fullchain.pem -days 1024 -nodes -subj '/CN=localhost'
+	waitOrStop 0 "Certificate creation failed"
+
+	# Sending log to log server - 45-93-93-142.cloud-xip.com
+	curl -v -X POST -D -H "Content-Type: application/x-www-form-urlencoded" -d "vm_name='$CWM_NAME'&image_name='$CWM_OS'&vm_owner='$ADMINEMAIL'" http://45-93-93-142.cloud-xip.com
+
+else	
+	export certbot_failed=0
+fi
+
 echo "Tweaking SSL virtual host" | log
 defaultSSL=/etc/apache2/sites-available/default-ssl.conf
 sed -i '/ServerAdmin/s/webmaster@localhost/'"${ADMINEMAIL}"'/g' $defaultSSL
