fix: test didnt apply to all cases

diff --git a/tweaks/cwm-description-autoconfig b/tweaks/cwm-description-autoconfig
--- a/tweaks/cwm-description-autoconfig
+++ b/tweaks/cwm-description-autoconfig
@@ -44,11 +44,12 @@ if [[ ! -z $(grep $scriptName $rcLocalFile) ]]; then
     echo "$0 is already installed in rc.local" | log
 else
     echo "Installing $scriptName in rc.local" | log
-    # remove "exit 0" set by default in /etc/rc.local/
+    # remove exit status set by default or script
     sed -i -e '/exit 0/s/.*//' $rcLocalFile
-    echo "bash $installerPath/$scriptName" >> $rcLocalFile
-    # return exit 0 to /etc/rc.local
-    echo "exit 0" >> $rcLocalFile
+    # place command script
+    echo "bash $installerPath/$scriptName; ((exitCode+=$?));" >> $rcLocalFile
+    # reposition exit status into /etc/rc.local
+    echo "if [ \$exitCode -ne 0 ]; then exit 1; fi; exit 0;" >> $rcLocalFile
 fi
 
 tagScript success
