fix: exit code once for all scripts

diff --git a/tweaks/cwm-description-autoconfig b/tweaks/cwm-description-autoconfig
--- a/tweaks/cwm-description-autoconfig
+++ b/tweaks/cwm-description-autoconfig
@@ -46,11 +46,12 @@ else
     echo "Installing $scriptName in rc.local" | log
     # remove exit status set by default or script
     sed -i -e '/exit 0/s/.*//' $rcLocalFile
+    sed -i -e '/exit \$exitCode/s/.*//' $rcLocalFile
     # place command script
     echo "bash $installerPath/$scriptName" >> $rcLocalFile
-    echo "if [ \$? -ne 0 ]; then exit 1; fi;" >> $rcLocalFile
-    # reposition exit status into /etc/rc.local
-    echo "exit 0" >> $rcLocalFile
+    echo "if [ \$? -ne 0 ]; then exitCode=1; fi;" >> $rcLocalFile
+    # reposition exit status after script
+    echo "exit \${exitCode:-0}" >> $rcLocalFile
 fi
 
 tagScript success
