Update enable-ssl Adding fix for ssl issue for testing

diff --git a/tweaks/enable-ssl b/tweaks/enable-ssl
--- a/tweaks/enable-ssl
+++ b/tweaks/enable-ssl
@@ -8,7 +8,20 @@ elif [ -f "../include/startup.sh" ]; then
 fi
 
 execSpecial 3 '(fail|error)' certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${CWM_DOMAIN} ${CWM_DEBUG:+"--test-cert"}
-waitOrStop 0 "Failed certbot certificate generation"
+###OREN CHANGES###
+if [[ $? == 1 ]]
+then
+certbot_failed=1
+echo "Generating self-signed certificate" | log
+mkdir /etc/letsencrypt/live
+mkdir /etc/letsencrypt/live/${CWM_DOMAIN}
+openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/letsencrypt/live/${CWM_DOMAIN}/privkey.pem -out /etc/letsencrypt/live/${CWM_DOMAIN}/fullchain.pem -days 1024 -nodes -subj '/CN=localhost'
+waitOrStop 0 "Certificate creation failed"
+else
+certbot_failed=0
+#waitOrStop 0 "Failed certbot certificate generation"
+fi
+
 export CWM_DISPLAYED_ADDRESS="${CWM_DOMAIN}"
 tag global-domain-set.success
 
