Changing asnible script to support cc

diff --git a/services/ansible-latest-osrepo b/services/ansible-latest-osrepo
--- a/services/ansible-latest-osrepo
+++ b/services/ansible-latest-osrepo
@@ -12,8 +12,7 @@ echo "Installing Ansible from APT" | log
 installPackage ansible | log
 waitOrStop 0 "Failed apt install: Ansible"
 
-# Coment zone
-: '
+
 
 # Get ansible Role
 ansible-galaxy install severalnines.clustercontrol | log
@@ -34,8 +33,65 @@ EOF
 # Run playbook
 ansible-playbook cc.playbook | log
 
-'
-#end comment zone
+####AFTER ANSIBLE PART:
+echo "after ansible part" | log
+
+#### SSL ####
+echo "Installing certbot for apache" | log
+installPackage python3-certbot-apache
+waitOrStop 0 "Failed apt install: python-certbot-apache"
+
+
+## applying ssl for cc web app ##
+systemctl stop apache2.service
+execSpecial 3 '(fail|error)' certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${CWM_DOMAIN} ${CWM_DEBUG:+"--test-cert"}
+###OREN CHANGES###
+if [[ $? == 1 ]]
+then
+export certbot_failed=1
+echo "Generating self-signed certificate" | log
+#waitOrStop 0 "Failed certbot certificate generation"
+mkdir /etc/letsencrypt/live
+mkdir /etc/letsencrypt/live/${CWM_DOMAIN}
+openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/letsencrypt/live/${CWM_DOMAIN}/privkey.pem -out /etc/letsencrypt/live/${CWM_DOMAIN}/fullchain.pem -days 1024 -nodes -subj '/CN=localhost'
+waitOrStop 0 "Certificate creation failed"
+
+# Sending log to log server - 45-93-93-142.cloud-xip.com
+curl -v -X POST -D -H "Content-Type: application/x-www-form-urlencoded" -d "vm_name='$CWM_NAME'&image_name='$CWM_OS'&vm_owner='$ADMINEMAIL'" http://45-93-93-142.cloud-xip.com
+
+
+else
+export certbot_failed=0
+fi
+
+export CWM_DISPLAYED_ADDRESS="${CWM_DOMAIN}"
+systemctl start apache2.service
+waitOrStop 0 "Failed to start Apache service"
+tag global-domain-set.success
+
+
+echo "Reconfigure SSL in Vhost" | log
+sed -i "s|^[ \t]*SSLCertificateFile.*|SSLCertificateFile /etc/letsencrypt/live/$CWM_DOMAIN/fullchain.pem|g" /etc/apache2/sites-available/s9s-ssl.conf
+sed -i "s|^[ \t]*SSLCertificateKeyFile.*|SSLCertificateKeyFile /etc/letsencrypt/live/$CWM_DOMAIN/privkey.pem|g" /etc/apache2/sites-available/s9s-ssl.conf
+waitOrStop 0 "Failed Reconfigure SSL in Vhost"
+systemctl restart apache2.service
+waitOrStop 0 "Failed restart apache2.service"
+
+#### SSL END ####
+
+## Remove Ansible ##
+apt-get remove -y ansible
+
+
+echo "Adding descriptions" | log
+descriptionAppend "!!!! Before first registration, please run: /var/www/html/clustercontrol/app/tools/reset-ccrpc.sh "
+descriptionAppend "cmon config files location: /etc/cmon.cnf"
+descriptionAppend "mariaDB user password: ${ADMINPASSWORD}"
+descriptionAppend "clustercontrol web page: ${CWM_DOMAIN}/clustercontrol"
+descriptionAppend "clustercontrol webpage config files location: /var/www/clustercontrol/bootstrap.php"
+descriptionAppend " "
+
+
 
 echo "Adding descriptions" | log
 descriptionAppend "Default Inventory File: /etc/ansible/hosts"
