django

diff --git a/apps/django-latest-osrepo b/apps/django-latest-osrepo
--- a/apps/django-latest-osrepo
+++ b/apps/django-latest-osrepo
@@ -85,12 +85,21 @@ fi
 SETTINGS_FILE="$appPath/djangoproject/settings.py"
 sed -i "s/^DEBUG = True/DEBUG = False/" "$SETTINGS_FILE"
 sed -i "s|^ALLOWED_HOSTS = \[\]|ALLOWED_HOSTS = ['${CWM_DOMAIN}', '${CWM_SERVERIP}', 'localhost', '127.0.0.1']|" "$SETTINGS_FILE"
+sed -i "s|^STATIC_URL = 'static/'|STATIC_URL = '/static/'|" "$SETTINGS_FILE"
 cat <<EOF >> "$SETTINGS_FILE"
 
 # Added by CWM installer (apps/django-latest-osrepo)
 CSRF_TRUSTED_ORIGINS = ['https://${CWM_DOMAIN}']
 SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
+STATIC_ROOT = '$appPath/staticfiles'
 EOF
+
+echo "Collecting Django static files" | log
+$appPath/django_env/bin/python3 $appPath/manage.py collectstatic --noinput
+if [ $? -ne 0 ]; then
+    echo "Failed to collect static files" | log 1
+    exit 1
+fi
 
 echo "Creating Django service" | log
 cat << EOF > /etc/systemd/system/django.service
@@ -137,6 +146,12 @@ server {
     location ~ \.php\$ {
         include snippets/fastcgi-php.conf;
         fastcgi_pass 127.0.0.1:9000;
+    }
+
+    location /static/ {
+        alias $appPath/staticfiles/;
+        access_log off;
+        expires 7d;
     }
 
     location = / {
