mod: checkInternetConnectivity format fix: apply exit code 99 where needed

diff --git a/include/checkInternetConnectivity b/include/checkInternetConnectivity
--- a/include/checkInternetConnectivity
+++ b/include/checkInternetConnectivity
@@ -8,63 +8,37 @@ elif [ -f "../include/startup.sh" ]; then
 fi
 
 success=0
+curlBaseParams=(--connect-timeout 10 --retry 3 --retry-connrefused --retry-delay 2 --max-time 30)
+domains=(www.cloudwm.com www.google.com www.yahoo.com)
+
 echo "Checking internet connectivity" | log
 
-echo "Trying to fetch www.cloudwm.com" | log
-curl "http://www.cloudwm.com/"  --connect-timeout 10 --retry 3 --retry-connrefused --retry-delay 2 --max-time 30 > /dev/null
+for domain in "${domains}"; do
 
-errorCode=$?
-if [ $errorCode -gt 0 ]; then
+    echo "Trying to fetch $domain" | log
+    curl "${curlBaseParams[@]}" --url "http://$domain/" > /dev/null
+    errorCode=$?
 
-    echo "Failed." | log
+    if [ $errorCode -ne 0 ]; then
 
-else 
+        echo "Failed." | log
+        continue
 
-    echo "Succeed." | log
-    ((success++))
-
-fi
-
-echo "Trying to fetch www.google.com" | log
-curl "http://www.google.com/"  --connect-timeout 10 --retry 3 --retry-connrefused --retry-delay 2 --max-time 30 > /dev/null
-
-errorCode=$?
-if [ $errorCode -gt 0 ]; then
-
-    echo "Failed." | log
-
-else
+    fi
 
     echo "Succeed." | log
     ((success++))
 
-fi
+done
 
-echo "Trying to fetch www.yahoo.com" | log
-curl "http://www.yahoo.com/"  --connect-timeout 10 --retry 3 --retry-connrefused --retry-delay 2 --max-time 30 > /dev/null
-
-errorCode=$?
-if [ $errorCode -gt 0 ]; then
-
-    echo "Failed." | log
-
-else
-
-    echo "Succeed." | log
-    ((success++))
-
-fi
-
-if [ "$success" -gt 0 ]; then 
-
-    echo "Test passed $success times. Test Passed. (0)" | log
-    tagScript success    
-    exit 0
-    
-else
+if [ $success -eq 0 ]; then 
 
     echo "Test passed $success times. Test Failed. (1)" | log 1
     tagScript failed
     exit 1
 
 fi
+
+echo "Test passed $success times. Test Passed. (0)" | log
+tagScript success    
+exit 0
